name: elex_driver
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  geolocator: ^13.0.2
  flutter_launcher_icons: ^0.14.0
  intl_phone_field: ^3.2.0
  image_picker: ^1.1.2
  go_router: ^14.8.1
  tuple: ^2.0.2
  mapbox_maps_flutter: ^2.6.1
  permission_handler: ^11.4.0
  location: ^8.0.0
  live_indicator: ^0.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  image: ^4.0.15

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Aptos
      fonts:
        - asset: fonts/aptos/Aptos-Light.ttf
          weight: 300
        - asset: fonts/aptos/Aptos-Light-Italic.ttf
          weight: 300
          style: italic
        - asset: fonts/aptos/Aptos.ttf
          weight: 400
        - asset: fonts/aptos/Aptos-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/aptos/Aptos-SemiBold.ttf
          weight: 600
        - asset: fonts/aptos/Aptos-SemiBold-Italic.ttf
          weight: 600
          style: italic
        - asset: fonts/aptos/Aptos-Bold.ttf
          weight: 700
        - asset: fonts/aptos/Aptos-Bold-Italic.ttf
          weight: 700
          style: italic
        - asset: fonts/aptos/Aptos-ExtraBold.ttf
          weight: 800
        - asset: fonts/aptos/Aptos-ExtraBold-Italic.ttf
          weight: 800
          style: italic
        - asset: fonts/aptos/Aptos-Black.ttf
          weight: 900
        - asset: fonts/aptos/Aptos-Black-Italic.ttf
          weight: 900
          style: italic
    - family: AptosNarrow
      fonts:
        - asset: fonts/aptos/Aptos-Narrow.ttf
          weight: 400
        - asset: fonts/aptos/Aptos-Narrow-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/aptos/Aptos-Narrow-Bold.ttf
          weight: 600
        - asset: fonts/aptos/Aptos-Narrow-Bold-Italic.ttf
          weight: 600
          style: italic
    - family: AptosSarif
      fonts:
        - asset: fonts/aptos/Aptos-Serif.ttf
          weight: 400
        - asset: fonts/aptos/Aptos-Serif-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/aptos/Aptos-Serif-Bold.ttf
          weight: 600
        - asset: fonts/aptos/Aptos-Serif-Bold-Italic.ttf
          weight: 600
          style: italic
    - family: AptosMono
      fonts:
        - asset: fonts/aptos/Aptos-Mono.ttf
          weight: 400
        - asset: fonts/aptos/Aptos-Mono-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/aptos/Aptos-Mono-Bold.ttf
          weight: 600
        - asset: fonts/aptos/Aptos-Mono-Bold-Italic.ttf
          weight: 600
          style: italic

    # Adding the new fonts you requested (Montserrat, Open Sans, and Raleway)
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat-BoldItalic.ttf
          weight: 700
          style: italic

    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic

    - family: Raleway
      fonts:
        - asset: assets/fonts/Raleway-Regular.ttf
        - asset: assets/fonts/Raleway-Bold.ttf
          weight: 700
        - asset: assets/fonts/Raleway-Italic.ttf
          style: italic
        - asset: assets/fonts/Raleway-BoldItalic.ttf
          weight: 700
          style: italic

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo mark.png"
  adaptive_icon_foreground: "assets/images/Logo 2.png"
  adaptive_icon_background: "assets/images/Logo.png"
