name: elex_driver
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  flutter_screenutil: ^5.9.3
  # google_maps_flutter: ^2.10.0
  geolocator: ^13.0.2
  # flutter_polyline_points: ^2.1.0
  # google_places_flutter: ^2.0.9
  flutter_launcher_icons: ^0.14.0
  intl_phone_field: ^3.2.0
  # flutter_map: ^7.0.2
  image_picker: ^1.1.2
  go_router: ^14.8.1
  tuple: ^2.0.2
  mapbox_maps_flutter: ^2.6.1
  permission_handler: ^11.4.0
  # lottie: ^3.3.1

  # mapbox_gl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

dependency_overrides:
  image: ^4.0.15 # Override to fix dependency conflict

flutter:
  uses-material-design: true

  assets:
    - assets/images/

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/Logo mark.png"
  adaptive_icon_foreground: "assets/images/Logo 2.png"
  adaptive_icon_background: "assets/images/Logo.png"
